
Parameters:
  MyKeyName:
    Description: select Ec2 key pair name
    Type: AWS::EC2::KeyPair::KeyName
  MyAZ:
    Description: Select the AZ
    Type: String
    Default: ap-south-1a
    AllowedValues:
      - ap-south-1c
      - ap-south-1b
      - ap-south-1a
    
Resources:
    myEC2Instance:
      Type: AWS::EC2::Instance
      Properties:
        KeyName: !Ref MyKeyName
        ImageId: ami-052cef05d01020f1d
        InstanceType: t2.micro
        SecurityGroupIds:
          - default
          - !Ref secGroupName
        AvailabilityZone: !Ref MyAZ
        Tags:
          - Key: Name
            Value: Demo-Instance
    secGroupName:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: My new SSH SG
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: '22'
            ToPort: '22'
            CidrIp: 0.0.0.0/0
          - IpProtocol: tcp
            FromPort: '8080'
            ToPort: '8080'
            CidrIp: 0.0.0.0/0
        Tags:
          - Key: Name
            Value: SSH-Security-Group
